name: minera_prueba
version: "0.1.0"
config-version: 2

profile: minera_prueba

model-paths:    ["models"]
macro-paths:    ["macros"]
seed-paths:     ["semillas"]
snapshot-paths: ["instantaneos"]
target-path:    "target"
clean-targets:  ["target", "dbt_packages"]

models:
  minera_prueba:
    bronce:
      +materialized: view
      +tags: ["capa:bronce", "dominio:codelco_andina"]
    silver:
      +materialized: incremental
      +incremental_strategy: append
      +unique_key: huella_registro
      +tags: ["capa:silver", "dominio:codelco_andina"]
      detalles:
        +unique_key: ["huella_registro", "valid_from"]
        +incremental_strategy: append
    oro:
      +tags: ["capa:oro", "dominio:codelco_andina"]

seeds:
  minera_prueba:
    +schema: semillas
    +tags: ["dominio:codelco_andina"]

snapshots:
  minera_prueba:
    +target_schema: instantaneos
    +tags: ["capa:instantaneo", "dominio:codelco_andina"]
